esphome:
  name: heatpumpcontroller
  platform: ESP32
  board: wesp32
  includes:
    - heatpumpcontroller.h
  libraries:
    - "HeatpumpIR"
    - "Adafruit BMP085 Library"

web_server:
  port: 80    

mqtt:
  broker: 192.168.0.101

ethernet:
  type: LAN8720
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0

i2c:
  sda: 33
  scl: 5
  scan: True  

sensor:
  - platform: bmp085
    temperature:
      id: bmp085_temperature
      name: "Outside Temperature"
    pressure:
      name: "Outside Pressure"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "Switch"    
    on_press:
      then:
        - climate.control:
            id: my_cliamte
            mode: COOL
            target_temperature: 21°C

climate:
  - platform: custom
    id: my_custom_climate
    lambda: |-
      auto my_custom_climate = new MyHeatPumpClimate(&bmp085_temperature);
      App.register_component(my_custom_climate);
      return {my_custom_climate};
    climates:
      - name: "My Custom Climate"
        id: my_cliamte

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "otapass"

ota:
  password: "otapass"
